// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'ai-parse-error'
  | 'ai-parse-error-disabled'
  | 'ai-parse-error-no-api-key'
  | 'ai-parse-error-no-content'
  | 'ai-parse-error-no-endpoint'
  | 'ai-parse-error-no-pdf'
  | 'ai-parse-error-no-regular-item'
  | 'ai-parse-error-no-selection'
  | 'ai-parse-progress-parsing'
  | 'ai-parse-progress-start'
  | 'ai-parse-result-complete'
  | 'ai-parse-result-failed'
  | 'ai-parse-result-items'
  | 'ai-parse-result-success'
  | 'menuitem-ai-parse'
  | 'pref-api-endpoint'
  | 'pref-api-key'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-max-tokens'
  | 'pref-model'
  | 'pref-section-api'
  | 'pref-section-display'
  | 'pref-section-model'
  | 'pref-section-prompt'
  | 'pref-show-header'
  | 'pref-system-prompt'
  | 'pref-temperature'
  | 'prefs-title';
