// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "apiEndpoint": string;
      "apiKey": string;
      "model": string;
      "systemPrompt": string;
      "temperature": number;
      "maxTokens": number;
      "showHeader": boolean;
    };
  }
}
